services:
  service-pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=connect

  service-redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes